"""add expected_start_date to proposal

Revision ID: 0125bdddb632
Revises: d7add7f39766
Create Date: 2026-05-06 15:42:11.176530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0125bdddb632'
down_revision: Union[str, Sequence[str], None] = 'd7add7f39766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('expected_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'expected_start_date')
    # ### end Alembic commands ###
