"""add terminated_at to person

Revision ID: 07d398b92125
Revises: 0125bdddb632
Create Date: 2026-05-06 16:10:19.913004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d398b92125'
down_revision: Union[str, Sequence[str], None] = '0125bdddb632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('terminated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'terminated_at')
    # ### end Alembic commands ###
