"""add company to person

Revision ID: 1de917db8492
Revises: 628ad9222ca4
Create Date: 2026-02-08 16:03:24.400295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de917db8492'
down_revision: Union[str, Sequence[str], None] = '628ad9222ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('company', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'company')
    # ### end Alembic commands ###
