"""add user groups

Revision ID: 2a59e13832d6
Revises: 2ee36a79e65e
Create Date: 2026-05-07 13:48:57.287059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a59e13832d6'
down_revision: Union[str, Sequence[str], None] = '2ee36a79e65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_group_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'area', name='uq_user_group_areas_group_area')
    )
    op.create_table('user_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_user_group_members_group_user')
    )

    # --- Seed: grupo "Acesso total" com todas as áreas + todos os usuários atuais ---
    AREAS = (
        "dashboard", "pessoas", "clientes", "contratos",
        "propostas", "farol", "capacidade", "gantt",
    )
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            "INSERT INTO user_groups (name, description) "
            "VALUES (:name, :desc)"
        ),
        {"name": "Acesso total", "desc": "Acesso a todas as áreas do sistema"},
    )
    group_id = result.lastrowid if hasattr(result, "lastrowid") else None
    if group_id is None:
        row = bind.execute(
            sa.text("SELECT id FROM user_groups WHERE name = :n"),
            {"n": "Acesso total"},
        ).first()
        group_id = row[0]
    for area in AREAS:
        bind.execute(
            sa.text(
                "INSERT INTO user_group_areas (group_id, area) "
                "VALUES (:g, :a)"
            ),
            {"g": group_id, "a": area},
        )
    user_rows = bind.execute(sa.text("SELECT id FROM users")).fetchall()
    for (uid,) in user_rows:
        bind.execute(
            sa.text(
                "INSERT INTO user_group_members (group_id, user_id) "
                "VALUES (:g, :u)"
            ),
            {"g": group_id, "u": uid},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_members')
    op.drop_table('user_group_areas')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
