"""add dates to contract_role

Revision ID: d7add7f39766
Revises: 48e0e947d460
Create Date: 2026-05-06 14:16:09.023021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7add7f39766'
down_revision: Union[str, Sequence[str], None] = '48e0e947d460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_roles', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('contract_roles', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_roles', 'end_date')
    op.drop_column('contract_roles', 'start_date')
    # ### end Alembic commands ###
